apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapichallenge-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swapichallenge
  template:
    metadata:
      labels:
        app: swapichallenge
    spec:
      containers:
      - name: swapichallenge
        image: swapichallenge
        ports:
        - containerPort: 8080
