apiVersion: v1
kind: Service
metadata:
  name: mercedeschallenge-service
spec:
  type: NodePort
  selector:
    app: mercedeschallenge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
